### ISSUE TITLE
Cannot connect to API

### ISSUE THREAD

**Issue by markuswesterberg** [nelbs/solaredge-forecast#1]
I have installed the integration successfully and configuration goes smoothly but the integration fails to connect via the API. What am I doing wrong? Says failed and no entities or units.
![Home_Assistant-fail-solaredge-forecast-screenshot](https://github.com/user-attachments/assets/9c34c50c-499c-4c18-9fcd-379118d0ae82)

**Comment by nelbs** [comment]
Have you enabled API access in the Solaredge web portal? And do you have at least 1 year of historical data? 

You could try if the api works with the example from the solaredge python package.  https://pypi.org/project/solaredge/

**Comment by markuswesterberg** [comment]
Looks like this in admin in SolarEdge. API-key greyed out.

![Administration_screen](https://github.com/user-attachments/assets/49b38876-8b25-4154-bbac-45010cbadb93)

Not sure how to use the python package you provided, sorry.

**Comment by nelbs** [comment]
For me it is not greyed out but that shouldn't be a problem i think.

Are there any warnings or errors in the logs?

**Comment by markuswesterberg** [comment]
No, I meant that I have mysself greyed out the sensitive data (key etc.) :)

I don't know if you can help and see something from below from the log:

2024-09-05 14:48:16.543 DEBUG (MainThread) [custom_components.solaredge_forecast] Finished fetching Solaredge Forecast data in 0.304 seconds (success: False)
2024-09-05 14:48:18.061 WARNING (MainThread) [custom_components.localtuya.common] Missing device configuration for device_id 1615871624a1602a5875
2024-09-05 14:48:18.067 WARNING (MainThread) [custom_components.localtuya.common] [511...3d1] Failed to connect to 10.0.0.23: [Errno 113] Connect call failed ('10.0.0.23', 6668)
2024-09-05 14:48:18.068 WARNING (MainThread) [custom_components.localtuya.common] [511...0f3] Failed to connect to 10.0.0.54: [Errno 113] Connect call failed ('10.0.0.54', 6668)
2024-09-05 14:48:21.515 WARNING (MainThread) [custom_components.localtuya.common] Missing device configuration for device_id 65035601ecfabc6689da
2024-09-05 14:48:22.794 WARNING (MainThread) [custom_components.localtuya.common] Missing device configuration for device_id 1615871624a1602a5875
2024-09-05 14:48:24.386 WARNING (MainThread) [custom_components.localtuya.common] [bfc...hpl] Failed to connect to 10.0.0.44: [Errno 110] Connect call failed ('10.0.0.44', 6668)
2024-09-05 14:48:25.860 WARNING (MainThread) [custom_components.localtuya.common] Missing device configuration for device_id 65035601ecfabc6689da
2024-09-05 14:48:28.528 WARNING (MainThread) [custom_components.localtuya.common] Missing device configuration for device_id 1615871624a1602a5875
2024-09-05 14:48:30.890 WARNING (MainThread) [custom_components.localtuya.common] Missing device configuration for device_id 65035601ecfabc6689da
2024-09-05 14:48:32.783 WARNING (MainThread) [custom_components.localtuya.common] Missing device configuration for device_id 1615871624a1602a5875
2024-09-05 14:48:36.170 WARNING (MainThread) [custom_components.localtuya.common] Missing device configuration for device_id 65035601ecfabc6689da
2024-09-05 14:48:37.717 WARNING (MainThread) [custom_components.localtuya.common] Missing device configuration for device_id 1615871624a1602a5875
2024-09-05 14:48:37.931 ERROR (MainThread) [custom_components.solaredge_forecast] Unexpected error fetching Solaredge Forecast data
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3791, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 152, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 181, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 4484, in pandas._libs.hashtable.Int32HashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 4508, in pandas._libs.hashtable.Int32HashTable.get_item
KeyError: 12

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solaredge_forecast/__init__.py", line 126, in _async_update_data
    data = await self.hass.async_add_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solaredge_forecast/solaredgeforecast/__init__.py", line 22, in __init__
    data = self.get_solar_forecast()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solaredge_forecast/solaredgeforecast/__init__.py", line 77, in get_solar_forecast
    daily['energy'] = daily.apply(average, axis=1)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pandas/core/frame.py", line 10034, in apply
    return op.apply().__finalize__(self, method="apply")
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pandas/core/apply.py", line 837, in apply
    return self.apply_standard()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pandas/core/apply.py", line 965, in apply_standard
    results, res_index = self.apply_series_generator()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pandas/core/apply.py", line 981, in apply_series_generator
    results[i] = self.func(v, *self.args, **self.kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solaredge_forecast/solaredgeforecast/__init__.py", line 76, in average
    return averages[row["month"]]
           ~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pandas/core/series.py", line 1040, in __getitem__
    return self._get_value(key)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pandas/core/series.py", line 1156, in _get_value
    loc = self.index.get_loc(label)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3798, in get_loc
    raise KeyError(key) from err
KeyError: 12
2024-09-05 14:48:37.934 DEBUG (MainThread) [custom_components.solaredge_forecast] Finished fetching Solaredge Forecast data in 0.292 seconds (success: False)
2024-09-05 14:48:40.868 WARNING (MainThread) [custom_components.localtuya.common] Missing device configuration for device_id 65035601ecfabc6689da
2024-09-05 14:48:42.709 WARNING (MainThread) [custom_components.localtuya.common] Missing device configuration for device_id 1615871624a1602a5875
2024-09-05 14:48:45.888 WARNING (MainThread) [custom_components.localtuya.common] Missing device configuration for device_id 65035601ecfabc6689da

**Comment by nelbs** [comment]
seems something went wrong with the calculation. Do you have at least 1 year of data from solaredge? And could you share your configuration (without the id and api)?

**Comment by markuswesterberg** [comment]
Yes, I believe I should have about 14 months of data.

Which file do you need? See below:

![Cursor_och_Studio_Code_Server_–_Home_Assistant](https://github.com/user-attachments/assets/96dbbe0b-d373-43ac-8399-a640b8ce1738)

**Comment by nelbs** [comment]
I mean the configuration variables from the integration, like these...

![image](https://github.com/user-attachments/assets/d00dce93-5817-4b4c-b361-9639410b03bc)

**Comment by markuswesterberg** [comment]
Ah, yes I used the same as you except I didn't put anything in the OPTIONAL last box.

**Comment by nelbs** [comment]
Unfortunately i cant reproduce your issue. I removed my input in the last field but everything keeps working.
You could try to change config parameters or add the start date in the last box.

**Comment by markuswesterberg** [comment]
I have no issue connecting to the API with SolarEdges own integration so this definitely is an issue specific to this integration. Could it have something to do with the fact that I changed hardware for the inline meter when I upgraded the system last month to backup-ready with the backup-unit with built-in meter you think?

**Comment by nelbs** [comment]
The only thing I can think of is that the integration does not have enough data to make the forecast. Based on this line

 `File “/usr/local/lib/python3.12/site-packages/pandas/core/indexes/base.py”, line 3798, in get_loc raise KeyError(key) from err KeyError: 12`. 

I suspect it cannot retrieve the data for the 12th month. If you look in the SolarEdge app, do you see data for more than a year?”

**Comment by markuswesterberg** [comment]
I have data starting July 2023. See below from the app:

![IMG_1747](https://github.com/user-attachments/assets/8f1b73e3-cdf2-4544-95fa-3e7ef5a29563)

**Comment by markuswesterberg** [comment]
Any more ideas? :)

**Comment by nelbs** [comment]
Well I noticed that your app looks different than mine. I also dont have a battery. Maybe the structure of the data you receive from the api is also different. Because I cannot debug the errors you get I is hard for me to solve it.

**Comment by markuswesterberg** [comment]
OK, sure I understand. It's a pity because I fail to get good enough forecasts with other integrations it seems and I would really like to get this integration to work!

**Comment by markuswesterberg** [comment]
Attaching the debug log here if you can see something from that?

[home-assistant_solaredge_forecast_2024-09-10T14-14-57.954Z.log](https://github.com/user-attachments/files/16946251/home-assistant_solaredge_forecast_2024-09-10T14-14-57.954Z.log)

**Comment by AnthonyBe** [comment]
I just installed and was seeing exact same problem. 
During setup, I left the last optional field empty. I then noticed in the failing query string that it had defaulted to looking for data since 2017!
I re-ran the integration configuration and added a date into the optional field (I have about 5 years of data so just went with 01012020) and then the integration started to work.

**Comment by markuswesterberg** [comment]
Tried that as well but won't work with the field filled out either. May be
something wrong with the data from my system, even though I can see history
in the monitoring from more than a year ago.


--

Markus Westerberg


Den ons 9 okt. 2024 kl 15:53 skrev Anthony ***@***.***>:
